/* DO NOT EDIT
     File automatically generated by make_blockmatch.pl from tokdefs.h
*/
#define MIN_CLOSER 286
#define MAX_CLOSER 309
#define MIN_BLOCK_TOKEN 283
#define MAX_BLOCK_TOKEN 339

337,0,0,0,0,0,0,0,0,0,
0,0,0,0,317,0,283,296,0,315,
317,331,337,339,
